POST http://localhost:8080/upload HTTP/1.1

Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"

title
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="z.png"
Content-Type: image/png

< ./z.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###